- name: Print a paramater
  hosts: localhost
  connection: local
  tasks:
    - name: print a parameter
      ansible.builtin.debug:
        msg: parameter - {{ lookup('aws_ssm', 'prasanna.1', region='us-east-1') }}